############# English navigation ##############

# main menu
[[main]]
name = "Le Low-tech lab"
url = "/"
weight = 1

[[main]]
name = "La low-tech"
url = "/low-tech"
weight = 2

[[main]]
name = "Les outils"
url = "#"
weight = 3

[[main]]
parent = "Les outils"
name = "Le wiki / les tutos"
url = "/tutorials"
weight = 1

[[main]]
parent = "Les outils"
name = "L'annuaire"
url = "/annuaire"
weight = 2

[[main]]
parent = "Les outils"
name = "L'agenda"
url = "/agenda"
weight = 3

[[main]]
parent = "Les outils"
name = "Contribuer"
url = "/contribuer"
weight = 4

[[main]]
parent = "Les outils"
name = "Ressources documentaires"
url = "/ressources-documentaires"
weight = 5

[[main]]
name = "Actualités / Blog"
url = "/actu-blog"
weight = 4


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
