backend:
  name: gitea
  repo: simsim/dev-hugo-site
  branch: main
  app_id: 4b3a0fb6-1742-4ec3-91a1-b73eb02f3187
  base_url: http://localhost:3000

media_folder: static/images
public_folder: /images

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'tutorials'
    label: 'Tutorials'
    folder: 'content/english/tutorials'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Meta Title', name: 'meta_title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Categories', name: 'categories', widget: 'list', required: false }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Difficulty', name: 'difficulty', widget: 'select', options: ['Easy', 'Medium', 'Hard'] }
      - { label: 'Duration', name: 'duration', widget: 'string' }
      - { label: 'Cost', name: 'cost', widget: 'string' }
      - { label: 'License', name: 'license', widget: 'string', default: 'CC BY-SA' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
